# Generated by Django 6.0.3 on 2026-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('carts', '0004_alter_cart_customer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer',), name='unique_active_cart_per_customer'),
        ),
    ]
